name: Build and Upload

on: [push]

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          - os: windows-2022
            os_name: windows
            arch: x86_64
            arch_name: amd64
          - os: windows-2022
            os_name: windows
            arch: arm64
            arch_name: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable with Nuitka (Windows Specific)
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          include-package: "websockets"
          python-flag: "-OO --assume-architecture=${{ matrix.arch }}"
          include-plugin-directory: "utils"
          output-dir: .
          output-file: marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}
          path: |
            ./marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}.exe


  build-linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            os_name: linux
            arch: x86_64
            arch_name: amd64
          - os: ubuntu-20.04
            os_name: linux
            arch: arm64
            arch_name: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install your Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          include-package: "websockets"
          include-module: "_bisect,_json"
          python-flag: "-OO --assume-architecture=${{ matrix.arch }}"
          output-dir: .
          include-plugin-directory: "utils"
          output-file: marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}.bin

      - uses: actions/upload-artifact@v4
        with:
          name: marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}
          path: |
            ./marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}.bin
