name: Build and Release

on:
  push:
    tags:
        - '*'
jobs:
  build-windows:
    strategy:
      matrix:
        platform:
          - amd64
    runs-on: windows-2022

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable with Nuitka (Windows Specific)
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          include-package: "websockets"
          python-flag: "-OO --assume-architecture=${{ matrix.arch }}"
          include-plugin-directory: "utils"
          output-dir: .
          output-file: marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}
          path: |
            ./marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}.exe


  build-linux:
    strategy:
      matrix:
        platform:
          - amd64
    runs-on: ubuntu-20.04
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install your Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          include-package: "websockets"
          include-module: "_bisect,_json"
          python-flag: "-OO --assume-architecture=${{ matrix.arch }}"
          output-dir: .
          include-plugin-directory: "utils"
          output-file: marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}.bin

      - uses: actions/upload-artifact@v4
        with:
          name: marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}
          path: |
            ./marzban_iplimit_${{ matrix.arch_name }}_${{ matrix.os_name }}.bin


  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts (AMD64) Linux
        uses: actions/download-artifact@v4
        with:
          name: marzban_iplimit_amd64_linux
          path: ./artifacts/amd64_linux

      - name: Download artifacts (ARM64) Linux
        uses: actions/download-artifact@v4
        with:
          name: marzban_iplimit_arm64_linux
          path: ./artifacts/arm64_linux

      - name: Download artifacts (AMD64) Windows
        uses: actions/download-artifact@v4
        with:
          name: marzban_iplimit_amd64_windows
          path: ./artifacts/amd64_windows

      - name: Download artifacts (ARM64) Windows
        uses: actions/download-artifact@v4
        with:
          name: marzban_iplimit_arm64_windows
          path: ./artifacts/arm64_windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading AMD64 files..."
          gh release upload ${{ github.ref_name }} ./artifacts/amd64_linux/marzban_iplimit_amd64_linux.bin

          echo "Uploading ARM64 files..."
          gh release upload ${{ github.ref_name }} ./artifacts/arm64_linux/marzban_iplimit_arm64_linux.bin

          echo "Uploading AMD64 files..."
          gh release upload ${{ github.ref_name }} ./artifacts/amd64_windows/marzban_iplimit_amd64_windows.exe

          echo "Uploading ARM64 files..."
          gh release upload ${{ github.ref_name }} ./artifacts/arm64_windows/marzban_iplimit_arm64_windows.exe